### ISSUE TITLE
iexec init fetcherror with docker

### ISSUE THREAD

**Issue by simplelins** [iExecBlockchainComputing/iexec-sdk#110]
docker command: docker run -e DEBUG=$DEBUG --interactive --tty --rm -v /tmp:/tmp -v $(pwd):/iexec-project -v /home/$(whoami)/.ethereum/keystore:/home/node/.ethereum/keystore -w /iexec-project iexechub/iexec-sdk:2.2.39 init

Error: 
ℹ using chain [ropsten]
⢀⠀ ▶ logging into iExec...

✖ command "iexec init" failed with FetchError: request to https://auth.iex.ec/typedmessage failed, reason: getaddrinfo ENOTFOUND auth.iex.ec auth.iex.ec:443

how can i access  https://auth.iex.ec ？

**Comment by PierreJeanjacquot** [comment]
Hi @simplelins,
The iExec SDK version v2.2.39 is no longer supported, logging into auth.iex.ec was part of the legacy workflow. This step was dropped with the v3 release.
Please use the current version v4.
