### ISSUE TITLE
show nRLC unit in iexec account command 

### ISSUE THREAD

**Issue by ericr6** [iExecBlockchainComputing/iexec-sdk#111]
It should be great to keep consistency with unit for "iexec account and "iexec wallet" commands 

iexec wallet show ...
ℹ Current wallet address .....
ℹ using chain [bellecour]
✔ Wallet bellecour balances [134]:
nRLC: 0

iexec account  show .... 
ℹ Current account address 0x....
ℹ using chain [bellecour]
✔ Account balances:
stake:  2000000000
locked: 0

**Comment by PierreJeanjacquot** [comment]
Not sure to understand, both commands display amount in nRLC.

**Comment by ericr6** [comment]
I meant the unit display
 
Account balances: (nRLC)
or
stake: 2000000000  (nRLC)
locked: 0   (nRLC)

**Comment by PierreJeanjacquot** [comment]
From v5.0.1, cryptocurrencies amount in CLI are formated using the main unit (`ether` or `RLC`)
Added explicit unit for amounts where it was missing.

```
$ iexec wallet show
ℹ Using chain [goerli]
✔ Wallet goerli balances [5]:
ether: 73.313786426379156445
RLC:   24.899312229
```
```
$ iexec account show
ℹ Using chain [goerli]
✔ Account balances (RLC):
stake:  7.038446818
locked: 0.0
```
