### ISSUE TITLE
Show stdout of tasks

### ISSUE THREAD

**Issue by zguesmi** [iExecBlockchainComputing/iexec-sdk#124]
After discussing this [issue](https://github.com/iExecBlockchainComputing/iexec-core/pull/381), it was closed since displaying the stdout of executions is not the responsibility of the scheduler.
The suggestion was that the SDK could maybe fetch this metadata for the user.

Thoughts?

**Comment by PierreJeanjacquot** [comment]
off-chain task debugging added in `v7.2.0`

- workerpool manager needs to configure an address to URL resolution with `iexec workerpool set-api-url <url>` to enable task debugging
- anyone can use `iexec workerpool show <address>` to check the configured `url`
- requester can use `iexec task debug <taskid> --logs` to get the app logs from a workerpool
- anyone can use `iexec task debug <taskid>` to get the task status metadata from the workerpool
