### ISSUE TITLE
SDK is configured by default with Viviani

### ISSUE THREAD

**Issue by gfedak** [iExecBlockchainComputing/iexec-sdk#186]
gitpod /workspace/iexec-sdk (master) $ iexec info
ℹ Using chain viviani [chainId: 133]
ℹ Ethereum host: default
✔ iExec contracts addresses:
iExec PoCo version:          5.3.0 standard
native RLC:                  true
iExec contract address:      0x3eca1B216A7DF1C7689aEb259fFB83ADFB894E7f
app registry address:        0xB1C52075b276f87b1834919167312221d50c9D16
dataset registry address:    0x799DAa22654128d0C64d5b79eac9283008158730
workerpool registry address: 0xC76A18c78B7e530A165c5683CB1aB134E21938B4

**Comment by PierreJeanjacquot** [comment]
`viviani` is removed in the next major version, the default chain for SDK CLI will be `bellecour`

The next version is available in alpha release and can be installed with `npm i -g iexec@alpha`.
Once installed, if you already have a `chain.json` you must overwrite it with `iexex init`
