### ISSUE TITLE
Callback stdout usage possible for docker app 

### ISSUE THREAD

**Issue by branciard** [iExecBlockchainComputing/iexec-sdk#30]
When an application is dockerise. Today, the result is always a zip file. For some apps, the stdout is needed in the smart contract after the bridge callback.

If the docker execution produces only a stdout file. This stdout will be pushed into the smart contract.
If the docker execution produces more than one files. It will be a zip as a result as today.

**Comment by lodygens** [comment]
a zip file is not only created if there is more that one file, but if the single file if more than 250Kb too

**Comment by branciard** [comment]
fixed in : iexec-sdk :
https://github.com/iExecBlockchainComputing/iexec-sdk/tree/v1.6.8
https://github.com/iExecBlockchainComputing/xtremweb-hep/releases/tag/12.2.10

testnet updated.
