### ISSUE TITLE
Fix docker execution on iExec to obtain the same behaviour as a local docker execution 

### ISSUE THREAD

**Issue by branciard** [iExecBlockchainComputing/iexec-sdk#33]
When a Dockerfile has : 
COPY / /

Files present at / in file are then not found at execution on iExec platform.

It will be fixed and the solution and impact ( for dirinuri and result path ) will be described in this issue.

**Comment by mocamircea** [comment]
Thanks!

**Comment by branciard** [comment]
In order for the docker execution to work as the local one, impacts are for inputs and outputs coming from iexec.  now there will be a specific folder /iexec : files coming from dirinuri will be found in /iexec/. If your execution, generate a result you want to see in your zip result, must put them in /iexec

**Comment by branciard** [comment]
Fixed in iexec-sdk https://github.com/iExecBlockchainComputing/iexec-sdk/releases/tag/v1.7.3. Deployed in testnet.

**Comment by branciard** [comment]
**Your result must be pushed in to appear in the zip result: /iexec 
Your dirinuri file can be found in : /iexec**
