### ISSUE TITLE
Define the name of the result in iexec result command

### ISSUE THREAD

**Issue by ericiexec** [iExecBlockchainComputing/iexec-sdk#36]
It should be useful to define the result filename 
iexec result ..... --savefile filename.zip

**Comment by Cold-A-Muse** [comment]
I second this! Would make everything just a little bit easier :)

**Comment by sulliwane** [comment]
close as fixed in https://github.com/iExecBlockchainComputing/iexec-sdk/commit/c87de0474796379a6c9c1c8ec8661788db4b1fe8 (v1.7.6)
