### ISSUE TITLE
Show explicit error message when filling a MarketOrder that does not exist

### ISSUE THREAD

**Issue by lodygens** [iExecBlockchainComputing/iexec-sdk#40]

**Comment by lodygens** [comment]
When trying to fill a MarketOrder that does not exist, the iexec SDK should print a explicit message.
Currently the message is:
✖ command "iexec order fill" failed with Error: [ethjs-abi] while encoding address, invalid address value, not alphanumeric 20 byte hex string

**Comment by sulliwane** [comment]
fixed in last version
