### ISSUE TITLE
sendETH did not work

### ISSUE THREAD

**Issue by trancept** [iExecBlockchainComputing/iexec-sdk#42]
With 2.2.8 sendETH did not work :
```
$ iexec wallet sendETH --to 0xF487fE0b04beDd03Dea15Ab441B8053cD947B78C 1
ℹ using chain [kovan]
✖ command "iexec wallet sendETH" failed with TypeError: Cannot destructure property `error` of 'undefined' or 'null'.
```

**Comment by sulliwane** [comment]
confirmed. Thanks for your report, the fix will be part of next release.

**Comment by sulliwane** [comment]
fixed in last version fixed in last version https://github.com/iExecBlockchainComputing/iexec-sdk/releases/tag/v2.2.12
