### ISSUE TITLE
Cannot read property 'getCookieByJWT'

### ISSUE THREAD

**Issue by trancept** [iExecBlockchainComputing/iexec-sdk#43]
$ iexec scheduler show
result in an error :
```
ℹ using chain [kovan]
⢀⠀ ▶ showing version...

✖ command "iexec scheduler show" failed with TypeError: Cannot read property 'getCookieByJWT' of undefined
```

**Comment by sulliwane** [comment]
Can you confirm you did run "iexec init" in the same folder where you are running "iexec scheduler show"?

**Comment by trancept** [comment]
Yes, the folder contain my Dapp and others command works well. But I don't need "iexec scheduler show" I'm not sure what it does.

**Comment by sulliwane** [comment]
Your ```kovan``` conf in ```chain.json``` file is probably missing the ```scheduler``` field, while it is a mandatory field. Latest sdk version reports a more explicit error.
