### ISSUE TITLE
"iexec account login" failed when passing SDK environment from one machine to another

### ISSUE THREAD

**Issue by jeremyjams** [iExecBlockchainComputing/iexec-sdk#50]
Subject: "iexec account login" failed when passing SDK environment from one machine to another

Situation:

```
$> ls
account.json
chain.json
iexec.json
wallet.json
```

```
$> iexec account login
ℹ using chain [dev]
⢀⠀ ▶ logging into iExec...

✖ command "iexec account login" failed with TypeError: Cannot read property 'getTypedMessage' of undefined
```

Patch to solve it:

```
cp wallet.json wallet.json.back
rm all (but not wallet.json.back)
iexec init
rm wallet.json
mv wallet.json.back wallet.json
iexec account login
```

SOLVED

**Comment by sulliwane** [comment]
Your dev conf in  ```chain.json``` file is probably missing the ```scheduler```` field, while it is a mandatory field. Last sdk version reports a more explicit error.

note: unnecessary ```rm``` step, directly run ```iexec init``` as it will always ask confirmation before overwriting any config file.
