### ISSUE TITLE
Incomplete deposit using the Docker image

### ISSUE THREAD

**Issue by ghisvail** [iExecBlockchainComputing/iexec-sdk#54]
I followed the [installation instructions](https://github.com/iExecBlockchainComputing/iexec-sdk#using-docker) and tried to deposit my first RLC to my account as explained in the README.

After running `iexec account deposit 200`, a transaction happened (my ETH balance got debited) but neither RLC got debited from my wallet nor credited to my account. The command kept running indefinitely and I had to terminate it eventually.

Meanwhile, using the `iexec`command installed with `npm` lead to a successful completion.

**Comment by PierreJeanjacquot** [comment]
Deposit command needs to perform two transactions (one to allow the hub to debit your wallet, one to deposit RLC from your wallet to the hub)
In your case the first transaction (allowance) has been mined but not the second one (deposit).
We encountered some sync problems using infura nodes that led to a fix in the latest SDK version.
