### ISSUE TITLE
UnhandledPromiseRejectionWarning of  http://localhost:8545 when using Kovan node

### ISSUE THREAD

**Issue by jeremyjams** [iExecBlockchainComputing/iexec-sdk#69]
If I try to execute an iExec SDK command on Kovan using an Infura node (for instance) while my local node 8545 is shutdown, I get an UnhandledPromiseRejectionWarning.

```
$ iexec workerpool deploy --chain kovan
ℹ using chain [kovan]
⢀⠀ ▶ deploying workerpool...(node:12227) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [ethjs-provider-http] Invalid JSON RPC response from provider
    host: http://localhost:8545
    response:  ""
    responseURL: undefined
    status: 0
    statusText: 
  
(node:12227) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ Deployed new workerpool at address 0x0blabla
```

I have the same situation when Infura isn't reachable and I'm using a local node (UnhandledPromiseRejectionWarning on Infura).

Thanks ;)

**Comment by PierreJeanjacquot** [comment]
This could happen when a node configured in chains.json is unreachable, this doesn't prevent the command to be correctly executed if the node is not your current chain node.
This will be fixed in next version 3.0.13
