### ISSUE TITLE
Error when submitting Factorial work with callback smart contract tutorial

### ISSUE THREAD

**Issue by Andy92Pac** [iExecBlockchainComputing/iexec-sdk#70]
When running the tutorial from this link https://docs.iex.ec/ordersubmit.html#using-a-custom-smart-contract-callback, the stdout result is 
 """
    usage: factorial.py [-h] [0-1000]
    factorial.py: error: too few arguments
    
  """
even if the m_params is set as expected with {“cmdline”: “10”}

**Comment by PierreJeanjacquot** [comment]
V2 outdated
