### ISSUE TITLE
iexec orderbook workerpool filter problem 

### ISSUE THREAD

**Issue by vladostp** [iExecBlockchainComputing/iexec-sdk#78]
At the marketplace in CAT 4 two different worker pools posted orders.
When I am trying to get order book of a worker pool with SDK, it returns orders of all worker pools.

**Comment by vladostp** [comment]
Command executed:
`iexec orderbook workerpool 0x54970649C446EeBD9d0e6469ce80F3eC61A9DAD1 --category 4 --chain kovan --raw`

**Comment by PierreJeanjacquot** [comment]
will be available in v3.0.24
