### ISSUE TITLE
gas required exceeds allowance or always failing transaction

### ISSUE THREAD

**Issue by voxsoftware** [iExecBlockchainComputing/iexec-sdk#81]
Deposit failed: gas required exceeds allowance or always failing transaction

I am trying to deposit 20 RLC on chain mainnet, using iexec from npm, and failed with that error

**Comment by PierreJeanjacquot** [comment]
Hi, do you have enough eth on you wallet to send the transaction?
Did you try to deposit on https://explorer.iex.ec ?
Can you give me your wallet address for transactions check?

**Comment by PierreJeanjacquot** [comment]
require more information, close
