### ISSUE TITLE
VM log for Launch worker

### ISSUE THREAD

**Issue by dietzam** [iExecBlockchainComputing/iexec-sdk#83]
I often get this ERROR in the VM log when I start the worker. I am not sure if it is significant ?

00:00:14.521032 VMMDev: Guest Log: 06:10:33.089339 main     vbglR3GuestCtrlDetectPeekGetCancelSupport: Supported (#1)
00:00:14.521117 ASSERT_GUEST_LOGREL F:\tinderbox\win-6.0\src\VBox\HostServices\GuestControl\VBoxGuestControlSvc.cpp(1119) int __cdecl GstCtrlService::clientMakeMeMaster(struct ClientState *,struct VBOXHGCMCALLHANDLE_TYPEDEF *,unsigned int): fRequestor != VMMDEV_REQUESTOR_LEGACY
00:00:14.521127 Outdated VBoxGuest w/o requestor support. Please update!
00:00:14.571359 VMMDev: Guest Log: 06:10:33.139651 main     Error: Failed to become guest control master: VERR_VERSION_MISMATCH
00:00:14.571537 VMMDev: Guest Log: 06:10:33.139853 main     Error: Service 'control' failed to initialize: VERR_VERSION_MISMATCH
00:00:14.571643 VMMDev: Guest Log: 06:10:33.139961 main     Session 0 is about to close ...
00:00:14.571677 VMMDev: Guest Log: 06:10:33.139999 main     Stopping all guest processes ...
00:00:14.571713 VMMDev: Guest Log: 06:10:33.140035 main     Closing all guest files ... when I startup the VM

**Comment by PierreJeanjacquot** [comment]
Hi dietzam,
It looks like there is something happening with virtual box.
Did you follow the [documentation](https://docs.iex.ec/worker.html#virtual-machine-vm)?
If you encounter a problem with the worker script, please open a issue in https://github.com/iExecBlockchainComputing/public-pool-scripts/issues

**Comment by dietzam** [comment]
my VB is standard 6.0.8. Maybe you are right this belongs to public-pool-scripts. If it happens again i open it there. Thanks
