### ISSUE TITLE
[iExec Explorer] unable to claim deal without tasks

### ISSUE THREAD

**Issue by SDxKeeper** [iExecBlockchainComputing/iexec-sdk#85]
It's not possible to claim deal which doesn't have tasks in iExec Explorer front end (even if deal is very old).
Example:
https://explorer.iex.ec/kovan/deal/0x3774019782a9184193c3672e5b1380309357b6f23f1c67fed7fc46bd29895b9d
https://explorer.iex.ec/kovan/deal/0x539b05ea45ca8e9c8fc13c8401ac05e0903bdad7f5e483f1bbfeadd69d70f241
https://explorer.iex.ec/kovan/deal/0x8210fc1edffe36683685b3991e056aeb253e787df5da434d8201a0d6dc5f63f5

P.S. Tasks were not started because of the malformed params field.

**Comment by PierreJeanjacquot** [comment]
Hi, 
Thank you for reporting, I fixed this in iExec explorer.
Claim should be available on deals with unstarted tasks.
