### ISSUE TITLE
on "iexec task show" correctly display hexadecimal result

### ISSUE THREAD

**Issue by sulliwane** [iExecBlockchainComputing/iexec-sdk#88]
Here I can see the results field "in clear" : https://explorer.iex.ec/kovan/task/0x1baa0932e32b6d303489e828e1a39c55045626faa754e8d3fa16e90e0cc1f984

But showing in the SDK return this:
![Screenshot from 2019-09-05 16-17-27](https://user-images.githubusercontent.com/1733686/64350258-ac3c9000-cff8-11e9-9461-6bc6f9942399.png)

Thanks!

**Comment by PierreJeanjacquot** [comment]
fixed in v3.1.0
