### ISSUE TITLE
[iExec Explorer] ipfs address is not readable

### ISSUE THREAD

**Issue by SDxKeeper** [iExecBlockchainComputing/iexec-sdk#89]
There are some strange hex/unicode sequence instead of dataset multiaddress for /ipfs located datasets
Example:
https://explorer.iex.ec/kovan/dataset/0xf54AF9FE68b92958F09f58fafD81e2DC13fda273

"MultiAddress:  ��|��eb��7J�8��BJ��Rϒ�5��e`U"

**Comment by PierreJeanjacquot** [comment]
Hi @SDxKeeper,
Multiaddr are now displayed as human readable.
Please notice that `/ipfs` is mapped to multiaddr protocol 421 with string representation `/p2p`. 
`/ipfs/QmFoo` is displayed as `/p2p/QmFoo` 

Read more about it:
https://github.com/libp2p/libp2p/issues/79
https://github.com/multiformats/js-multiaddr/pull/97

**Comment by SDxKeeper** [comment]
Hi @PierreJeanjacquot 

Nice, thanks!
