### ISSUE TITLE
node installation link 

### ISSUE THREAD

**Issue by ericr6** [iExecBlockchainComputing/iexec-sdk#95]
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04
maybe helpful to add the link

**Comment by PierreJeanjacquot** [comment]
https://github.com/iExecBlockchainComputing/iexec-sdk#using-nodejs

[![npm version](https://img.shields.io/badge/nodejs-%3E=%208.0.0-brightgreen.svg)](https://nodejs.org/en/) link to official website
